namespace datasheetapi.Models;

public class ElectricalPurchaserRequirement
{
    public string? OrderStatus { get; set; }
    public string? TagNumber { get; set; }
    public string? TagDescription { get; set; }
    public string? ClientName { get; set; }
    public string? SiteOrLocation { get; set; }
    public string? ProjectTitleOrNumber { get; set; }
    public string? PurchaseOrderNumber { get; set; }
    public string? Manufacturer { get; set; }
    public string? ModelNumber { get; set; }
    public string? IEEEStd841MotorType { get; set; }
    public string? AdditionalCertification { get; set; }
    public string? StartingMethod { get; set; }
    public string? NumberOfPolesMotorSynchronousSpeed { get; set; }
    public string? DirectionOfRotation { get; set; }
    public string? MethodOfMotorCouplingToDrivenEquipment { get; set; }
    public string? MotorRatedFrequency { get; set; }
    public string? MotorRatedVoltage { get; set; }
    public string? FrameSize { get; set; }
    public string? RatedPowerOutput { get; set; }
    public string? ServiceFactor { get; set; }
    public string? FullLoadCurrent { get; set; }
    public string? LoadType { get; set; }
    public string? MinimumOperatingSpeed { get; set; }
    public string? MaximumOperatingSpeed { get; set; }
    public string? FloatingMarineShipboard { get; set; }
    public string? ChemicalsOrCorrosives { get; set; }
    public string? Altitude { get; set; }
    public string? MinimumAmbientAirTemperature { get; set; }
    public string? MaximumAmbientAirTemperature { get; set; }
    public string? MotorDesignsAndStartingCharacteristics { get; set; }
    public string? RatedFullLoadSpeed { get; set; }
    public string? RatedFullLoadTorque { get; set; }
    public string? RatedBreakdownTorque { get; set; }
    public string? EfficiencyAt100PercentRatedOutput { get; set; }
    public string? EfficiencyAt75PercentRatedOutput { get; set; }
    public string? EfficiencyAt50PercentRatedOutput { get; set; }
    public string? PowerFactorAt100PercentRatedOutput { get; set; }
    public string? PowerFactorAt75PercentRatedOutput { get; set; }
    public string? PowerFactorAt50PercentRatedOutput { get; set; }
    public string? MaximumPermissibleSoundPressureAt1Meter { get; set; }
    public string? MotorSoundPressureAt1Meter { get; set; }
    public string? MotorWeight { get; set; }
    public string? StainlessSteelHardware { get; set; }
    public string? EnclosureType { get; set; }
    public string? EnclosureIngressProtection { get; set; }
    public string? FanMaterial { get; set; }
    public string? Position { get; set; }
    public string? IngressProtectionOfTerminalBoxes { get; set; }
    public string? MainTerminalBoxCableEntryHoleSizeAndNumber { get; set; }
    public string? OversizedTerminalBox { get; set; }
    public string? MainTerminalBoxMaterial { get; set; }
    public string? L10Life { get; set; }
    public string? DriveEndBearingNumber { get; set; }
    public string? NonDriveEndBearingNumber { get; set; }
    public string? ExternalRadialLoadingOnMotorShaftEnd { get; set; }
    public string? ExternalAxialLoadingOnMotorShaftEnd { get; set; }
    public string? RecommendedLubricant { get; set; }
    public string? Grease { get; set; }
    public string? OilMistLubricant { get; set; }
    public string? SealedForLifeAntiFrictionBearing { get; set; }
    public string? ASDFedMotorNonDriveEndInsulationBearingRequirement { get; set; }
    public string? SpaceHeater { get; set; }
    public string? SpaceHeaterTerminalBox { get; set; }
    public string? SpaceHeaterVoltage { get; set; }
    public string? WarningLabel { get; set; }
    public string? WarningLabelLanguage { get; set; }
    public string? MountingPosition { get; set; }
    public string? TypeOfMounting { get; set; }
    public string? FlangeType { get; set; }
    public string? VerticalMotorShaftOrientation { get; set; }
    public string? NonReverseRatchet { get; set; }
    public string? DripCover { get; set; }
    public string? VerticallyMountedMotorAdditionalRequirement { get; set; }
    public string? ProvisionsForVibrationMonitoring { get; set; }
    public string? WindingTemperatureDetectors { get; set; }
    public string? BearingTemperatureDetectors { get; set; }
    public string? InstrumentationTerminalBox { get; set; }
    public string? ProvisionForIoTHardwareInstallation { get; set; }
    public string? MotorMonitoringDevice { get; set; }
    public string? AtmosphericCorrosivityCategory { get; set; }
    public string? SurfaceProtectionDurabilityCategory { get; set; }
    public string? HazardousAreaClassification { get; set; }
    public string? UL674Listing { get; set; }
    public string? TemperatureGroup { get; set; }
    public string? GasDustGroup { get; set; }
    public string? ShopInspection { get; set; }
    public string? VibrationTest { get; set; }
    public string? AdditionalTest { get; set; }
    public string? StorageConditions { get; set; }
    public string? StorageDuration { get; set; }
    public string? MotorNameplateOilMistLubricated { get; set; }
    public string? MotorTemporaryTagOilMistReadyDoNotRunWithoutOil { get; set; }
    public string? MotorDataSheet { get; set; }
    public string? DeliveryOfMotorRoutineTestData { get; set; }
    public string? TorqueAndCurrentVSSpeedCurve { get; set; }
    public string? MotorThermalCurves { get; set; }
    public string? MaximumPermissibleStallTimeData { get; set; }
    public string? ASDOperationCurves { get; set; }
    public string? DimensionalOutlineDrawingShowingWeightLocationOfTerminalBoxesAndAccessories { get; set; }
    public string? InstallationOperationAndMaintenanceManuals { get; set; }
    public string? MotorConnectionDiagramIncludingAuxilliaries { get; set; }
    public string? AdditionalTestRecord { get; set; }
    public string? Certifications { get; set; }
    public string? SerialNumber { get; set; }
    public string? ConformityAssessmentSystemLevel { get; set; }
    public string? DutyType { get; set; }
    public string? NumberOfPoles { get; set; }
    public string? DutyPointShaftPower { get; set; }
    public string? MomentOfInertiaOfTheLoadJext { get; set; }
    public string? LocationEnvironment { get; set; }
    public string? StandstillPeriod { get; set; }
    public string? MaximumRelativeHumidity { get; set; }
    public string? ImpactProtection { get; set; }
    public string? ThermalClass { get; set; }
    public string? TemperatureRiseClass { get; set; }
    public string? MomentOfInertiaOfTheMotorJm { get; set; }
    public string? DataForProtectionSettingPowerModelling { get; set; }
    public string? TransportAndStorageConditions { get; set; }
    public string? Efficiency { get; set; }
    public string? PurchaserMaximumPermissibleNoiseLimit { get; set; }
    public string? MaximumDeclaredMotorSoundPowerLevelAtNoLoad { get; set; }
    public string? MaximumExpectedMotorSoundPowerLevelAtFullLoad { get; set; }
    public string? NoiseLevelTestAtOneMotorFromThisOrderBatch { get; set; }
    public string? StainlessSteelFixings { get; set; }
    public string? MaximumVibrationMagnitude { get; set; }
    public string? FanImpellerMaterial { get; set; }
    public string? FanDirectionOfRotation { get; set; }
    public string? TerminalBoxLocation { get; set; }
    public string? LineConductorTerminalBoxCableGlandEntries { get; set; }
    public string? LineConductorCrossSectionArea { get; set; }
    public string? LargeTerminalBox { get; set; }
    public string? DEndBearingType { get; set; }
    public string? NEndBearingType { get; set; }
    public string? InternalClearance { get; set; }
    public string? LubricationSpecification { get; set; }
    public string? HeaterRequirement { get; set; }
    public string? SupplyVoltage { get; set; }
    public string? SeperateTerminalBox { get; set; }
    public string? MountingArrangement { get; set; }
    public string? CoolingMethod { get; set; }
    public string? VibrationMonitoring { get; set; }
    public string? VibrationLevelTestReport { get; set; }
    public string? ShockPulseMonitoringConnection { get; set; }
    public string? SurfaceProtectionCorrosivityCategory { get; set; }
    public string? SurfaceFinish { get; set; }
    public string? PaintColor { get; set; }
    public string? WindingTemperatureDetection { get; set; }
    public string? ConverterManufacturer { get; set; }
    public string? ConverterModelNumber { get; set; }
    public string? FineBalancingAboveRatedSpeed { get; set; }
    public string? MotorToBeRatedForUseInPotentiallyExplosiveAtmosphere { get; set; }
    public string? HazardousAreaEquipmentCertifyingBody { get; set; }
    public string? EquipmentProtectionLevel { get; set; }
    public string? MotorClassification { get; set; }
    public string? LoadDrive { get; set; }
}
