name: Build
on:
  workflow_call:

jobs:
  build:
    name: '🛠️ Build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore datasheetapi/datasheetapi.csproj
    - name: Build
      run: dotnet build datasheetapi/datasheetapi.csproj --no-restore
    - name: Test
      run: dotnet test tests --no-build --verbosity normal


  docker:
    name: ''
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: |
          docker login -u ${{ secrets.DYNATRACE_PREPROD_TENANT }} spa-equinor.kanari.com -p ${{ secrets.DYNATRACE_PREPROD_TOKEN }}
          docker build --build-arg DYNATRACE_URL=spa-equinor.kanari.com --build-arg DYNATRACE_TENANT=${{ secrets.DYNATRACE_PREPROD_TENANT }} --build-arg DYNATRACE_PAAS_TOKEN=${{ secrets.DYNATRACE_PREPROD_TOKEN }} --build-arg environment=dev . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/datasheetapi:${{ github.sha }}