name: 🚀 Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        description: "Force deploy to prod"
        type: boolean
        default: false
        required: true

env:
  FUSION_APP_KEY: spinedatasheet  

jobs:
  build:
    name: Build
    uses: equinor/spinedatasheet/.github/workflows/build.yml@main
    
  release_please:
    name: 🔖 Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: spinereview
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"style", "section":"Cosmetic changes","hidden":false},
            {"type":"docs","section":"For developers","hidden":false},
            {"type":"refactor","section":"For developers","hidden":false},
            {"type":"ci", "section":"For developers","hidden":false},
            {"type":"chore", "section":"For developers","hidden":false},
            {"type":"perf", "section":"Optimalization","hidden":false}]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    
  deploy-ci:
    name: '🚀 CI'
    runs-on: ubuntu-latest
    needs: build
    environment: CI
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip
          
  deploy_qa:
    name: '🚀 QA'
    runs-on: ubuntu-latest
    needs: [release_please, deploy-ci]
    if: ${{ needs.release_please.outputs.release_created || inputs.force }}
    environment: QA
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip

  deploy_prod:
    name: '🚀 Prod'
    runs-on: ubuntu-latest
    needs: [deploy_qa]
    environment: PROD
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip
